base_config: ../config/
base_expid: SimpleX_base
dataset_id: yelp18_x0

dataset_config:
    yelp18_x0:
        data_root: ../data/Yelp18/
        data_format: csv
        train_data: ../data/Yelp18/yelp18_x0/train.csv
        valid_data: ../data/Yelp18/yelp18_x0/test.csv
        item_corpus: ../data/Yelp18/yelp18_x0/item_corpus.csv
        min_categr_count: 1
        query_index: query_index
        corpus_index: corpus_index
        feature_cols:
            - {'name': 'query_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'corpus_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'user_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'user'}
            - {'name': 'user_history', 'active': True, 'dtype': str, 'type': 'sequence', 'source': 'user', 'splitter': '^',
               'max_len': 500, 'padding': 'pre', 'embedding_callback': null}
            - {'name': 'item_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'item', 'share_embedding': 'user_history'}
        label_col: {name: label, dtype: float}

tuner_space:
    model_root: './Yelp18/SimpleX_yelp18_x0/'
    learning_rate: 1.e-4
    embedding_dim: 64
    num_negs: [1000]
    embedding_regularizer: [1.e-8]
    similarity_score: cosine
    loss: CosineContrastiveLoss
    user_id_field: user_id
    item_id_field: item_id
    user_history_field: user_history
    aggregator: mean
    gamma: [1]
    net_dropout: 0.1
    attention_dropout: 0
    negative_weight: [150]
    margin: 0.9
    enable_bias: False
    ignore_pos_items: False
    sampling_num_process: 1
    fix_sampling_seeds: False
    batch_size: 512
    seed: 2019
    monitor: Recall(k=20)

    
